version: "3"


services:
  #---------------------------------
  # Project Manager
  #---------------------------------
  project_manager:
    build:
      context: ./project_manager
    command: >
      sh -c "chmod 777 ./wait_for_postgres.sh &&
             ./wait_for_postgres.sh &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py loaddata base_model_data.json &&
             python manage.py runserver 0.0.0.0:8085"
    volumes:
      - ./project_manager:/code
    ports:
      - "8085:8085"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgresql

  #---------------------------------
  # DB for Project Manager
  #---------------------------------
  postgresql:
    image: postgres:latest
    restart: always
    volumes:
      - postgreSQL:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  

  

  #---------------------------------
  # Target Image Build 
  #---------------------------------
  target_image_build:
    build:
      context: ./target_image_build
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8088"
    volumes:
      - ./target_image_build:/source
    ports:
      - "8088:8088"

  #---------------------------------
  # Image Deployment 
  #---------------------------------
 
  #---------------------------------
  # Visualizer 
  #---------------------------------
  viz2code:
    build:
      context: ./visualization
    command: >
      sh -c "cd ./visualization/frontend &&
             npm run build &&
             cd ..
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver react 0.0.0.0:8091"
    volumes:
      - ./viz2code:/source
    ports:
      - "8091:8091"
    depends_on:
      - postgresql

#---------------------------------
# Volumes 
#---------------------------------
volumes:
  postgreSQL:  # for Proejct Manager
